// This file was generated by RedwoodJS
import AboutPageType from 'D:/NEXT6/red6.1-9/web/src/pages/AboutPage/AboutPage'
import FatalErrorPageType from 'D:/NEXT6/red6.1-9/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from 'D:/NEXT6/red6.1-9/web/src/pages/HomePage/HomePage'
import LoginPageType from 'D:/NEXT6/red6.1-9/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from 'D:/NEXT6/red6.1-9/web/src/pages/NotFoundPage/NotFoundPage'
import UserEditUserPageType from 'D:/NEXT6/red6.1-9/web/src/pages/User/EditUserPage/EditUserPage'
import UserNewUserPageType from 'D:/NEXT6/red6.1-9/web/src/pages/User/NewUserPage/NewUserPage'
import UserUserPageType from 'D:/NEXT6/red6.1-9/web/src/pages/User/UserPage/UserPage'
import UserUsersPageType from 'D:/NEXT6/red6.1-9/web/src/pages/User/UsersPage/UsersPage'

declare global {
  const AboutPage: typeof AboutPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const UserEditUserPage: typeof UserEditUserPageType
  const UserNewUserPage: typeof UserNewUserPageType
  const UserUserPage: typeof UserUserPageType
  const UserUsersPage: typeof UserUsersPageType
}
