// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './EditUserCell'
import type { EditUserById, EditUserByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditUserCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof EditUserById | 'updating'
> & EditUserByIdVariables

export default function (props: CellInputs): ReturnType<SuccessType>
