// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './UserCell'
import type { FindUserById, FindUserByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './UserCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindUserById | 'updating'
> & FindUserByIdVariables

export default function (props: CellInputs): ReturnType<SuccessType>
