// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './UsersCell'
import type { FindUsers, FindUsersVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './UsersCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindUsers | 'updating'
> & FindUsersVariables

export default function (props: CellInputs): ReturnType<SuccessType>
